### PR TITLE
Added April forecasts from Sentinel team

### PR DESCRIPTION
**Pull request by sdwfrost**
Here's a first set of forecasts. Here, we aimed to get 'null' models i.e. those that don't incorporate any additional information that may be better than a simple negative binomial fit. We tried three different approaches, and did not try to tweak them using the scoring function.

### CODE REVIEW

**Comment by sdwfrost** [comment]
Hi @cdcepi, I do want to upload multiple models, if that's OK. Please let me know if I have to do anything on my end to help push this through.

**Comment by ryandharp** [comment]
> Hi @cdcepi, I do want to upload multiple models, if that's OK. Please let me know if I have to do anything on my end to help push this through.

Hi @sdwfrost, thanks for checking in! It's perfectly acceptable to submit multiple models but you'll need to split up your models into separate "teams" (i.e. submissions) for processing purposes. Please let me know if you have additional questions.

**Comment by sdwfrost** [comment]
Thanks @ryandharp for merging this - I was travelling to Nigeria over the weekend, and so didn't see your message about splitting things up - I will do so in future.

**Comment by ryandharp** [comment]
You're quite welcome, @sdwfrost. I missed this earlier but when I merged this pull request the three models came through in three separate folders, which was perfect. So no changes needed on your end--feel free to repeat your process exactly moving forward. Thanks and safe travels!

**Pull request merged**
